In [108]:
import random
import numpy
import time
# Link to padding https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-9.php
# Link to reading csv into numpy https://stackoverflow.com/questions/3518778/how-do-i-read-csv-data-into-a-record-array-in-numpy

In [112]:
random.seed(1)

In [179]:
file_data = numpy.genfromtxt('./sample_grid.csv', delimiter=',')
grid = numpy.pad(file_data, pad_width=1, mode='constant', constant_values=0)
m = len(grid)
n = len(grid[0])
grid

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [167]:
m = 7#int(input()) # rows
n = 5 # columns
m += 2
n += 2
grid = []
for i in range(m):
    row = [0] * n
    if i == 0 or i == (m - 1):
        grid.append( row )
        continue 
    for j in range(len(row)):
        if j == 0 or j == (n - 1):
            row[j] = 0
        else:
            row[j]  = random.randint(0,1)
    grid.append( row )
grid = numpy.asarray(grid)
grid

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [120]:
def get_alive_neighbors(grid, i, j):
    n_alive = 0
    n_alive += grid[i-1][j-1]
    n_alive += grid[i-1][j]
    n_alive += grid[i-1][j+1]
    n_alive += grid[i][j+1]
    n_alive += grid[i+1][j+1]
    n_alive += grid[i+1][j]
    n_alive += grid[i + 1][j-1]
    n_alive += grid[i][j-1]
    
    return n_alive

In [180]:
# loop through each cell
while True:
    for i in range(m):
        for j in range(n):
            if i == 0 or i == (m - 1) or j == 0 or j == (n - 1):
                pass                           # skip if the cell is just a border cell
            else:
                n_alive_neighbors = get_alive_neighbors(grid, i, j)
                if grid[i][j] == 1:            # if the cell is alive
                    if n_alive_neighbors < 2:  # Живая клетка, у которой меньше двух живых соседей, погибает.
                        grid[i][j] = 0
                    if n_alive_neighbors > 3:
                        grid[i][j] = 0         # Живая клетка, у которой больше трёх живых соседей, погибает.
                else:                          # if the cell is dead
                    if n_alive_neighbors == 3:
                        grid[i][j] = 1         # Мёртвая клетка, у которой три живых соседа, возрождается.
#     for r in grid:
#         print(r)
    print(grid[1:-1,1:-1])
    print("\n")
    time.sleep(1)

[[0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0.]]


[[0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]]


[[0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


[[0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0.]]


[[0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]]


[[0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 0.]]


[[0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 0.]]


[[0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0.

KeyboardInterrupt: 

In [107]:
grid

[[0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 1, 1, 0],
 [0, 1, 0, 0, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0],
 [0, 0, 1, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0]]